import Head from "next/head";
import { type NextPage } from "next";

import { api } from "~/utils/api";


import { LoaderSpinner } from "~/components/loading";
import PostView from "~/components/PostVIew";
import PageLayout from "~/layouts/PageLayout";


const ProfileFeed = (props: {userId: string}) => {
  const { data, isLoading: postsLoading } = api.post.getPostsByUserId.useQuery({
    userId: props.userId
  })

  if (postsLoading)
    return <div className="pt-52 flex"><LoaderSpinner size={30} /></div>

  if (!data || !data.length)
    return <div>{"User hasn't posted"}</div>

  return (
    <div className="flex flex-col">
      {
        data.map((post) => (
          <PostView key={post.post.id} post={post} />
        ))
      }
    </div>
  )
}

const Home: NextPage = () => {
  // since React Query fetches only once, calling this in Page Component
  // makes sure React Query fetches the data ASAP
  api.post.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <ProfileFeed userId="" />
      </PageLayout>
    </>
  );
};

export default Home;
